Final
marcelomaidden/react-calculator-v1 pull request #4
Opened 2021-02-11 19:00 UTC by marcelomaidden

## Final
At this pull request, I add functionality for the buttons:
- Add clickHandler to perform math operations (+, -, X, /, %, +/-)
- Add style to the buttons passing the className via props
- Check if the last clicked button is an operation
- Use props and state to update the Virtual DOM
- Use big.js to handle big numbers

2021-02-11 20:51 UTC, Forison requested changes
## Status:: Change Required

# Hi Marcelo

#### You have done a good job on this one so far, Good job on styling the application even though it is not a requirement.

* [ ] The image in the in Readme is not showing.

* [ ] Kindly remove all `console.log` from the code.

* [ ] Kindly move the logic in the handleClick to calculate.js

* [ ] When a number is divided by zero, it should return undefined, not zero.

* [ ] When the modifier `+/-` is selected and number1 and number two are present, it should mutate both numbers not one. ie `4 + 5` after selecting `+/-` should become `-4 - 5` not `4-5`

**[OPTIONAL]**
The user experience could be improved by allowing users see both operand and the operator whilst performing a calculation.

#### That is it, kindly make the changes and submit a re-review.

#### Happy coding

Addo Forison

2021-02-11 20:51 UTC, Forison commented on src/components/App.js
> +    console.log(lastClicked);
let remove `console.log`, this is not a good practice as you may end up sending sensitive info.

2021-02-11 20:51 UTC, Forison commented on src/components/App.js
> +      this.setState({
let move this code calculate.js, handleclick would then rely on the logic in the calculate.js.

2021-02-11 21:55 UTC, marcelomaidden commented
Hello Forison. Thanks for pointing out where I need to improve my code. I would like to mention that '+/-' is already converting both numbers to the reverse (positive, negative). Together with this message, I send a screenshot from the code for conference.
![Screenshot from 2021-02-11 18-50-58](https://user-images.githubusercontent.com/2086674/107703635-abeafe80-6c9a-11eb-9a16-b47e44f694ec.png).

2021-02-12 00:21 UTC, uche-inyama requested changes
## Changes Required

### Hi @marcelomaidden :wave: 

The **+/-**  operation is not working properly; It does not work for division and multiplication. I will leave a git for reference. I also discovered that operation like(-8-2) returns +6 instead of -10.

![gif1](https://user-images.githubusercontent.com/46329537/107715863-6fd29080-6cd0-11eb-994e-eed7ac45ae23.gif)


Make the change then submit another form for a review.

### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

2021-02-12 20:10 UTC, christianotieno requested changes
## Changes Required ♻️ 

Hello @marcelomaidden 👋 
We have some few issues in the console, React is complaining about in which I have highlighted down below 👇 
### Happy coding 💻 
#### Christian Otieno (CR)

2021-02-12 20:10 UTC, christianotieno commented on src/components/Display.js
> +  }).isRequired,
## Fix this prop-error validation
- [ ] Hello, we have some informing errors in the console. Kindly fix these prop validations.
![prop-error](https://user-images.githubusercontent.com/22345961/107817477-40328f80-6d87-11eb-9727-3b5a138d6771.png)

2021-02-12 22:18 UTC, shloch approved these changes
## Hello @marcelomaidden 

This issue is diligently solved and based on that you get thumbs for the next step
![accomplished](https://user-images.githubusercontent.com/40712459/107828207-aa97ff80-6d88-11eb-9e9c-1e4cf6ceccf2.jpg)

HAPPY CODING

2021-02-12 22:18 UTC, shloch commented on src/components/Display.js
>  };
Awesome job, straight to the point

2021-02-12 22:39 UTC, marcelomaidden commented on src/components/Display.js
>  };
Thanks to all code reviewers.

2021-02-12 22:39 UTC, merged